defaultName: Roast and Brew
dbURL: jdbc:mysql://10.0.18.195:3306/coffee?autoReconnect=true&user=root&password=rootROOT&useSSL=false&useServerPrepStmts=false&allowPublicKeyRetrieval=false

server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001
